description: Putey Beta 1 Breadboard Computer
general:
  min_version: 0.3.0
  address_size: 16
  endian: little
  registers:
    - a
    - i
    - j
    - mar
operand_sets:
  8_bit_source:
    operand_values:
      a_register:
        type: register
        register: a
        bytecode:
          value: 0
          size: 3
      i_register:
        type: register
        register: i
        bytecode:
          value: 2
          size: 3
      j_register:
        type: register
        register: j
        bytecode:
          value: 3
          size: 3
      indirect_addr:
        type: indirect_numeric
        bytecode:
          value: 6
          size: 3
        argument:
          size: 16
          byte_align: true
      immediate_value:
        type: numeric
        bytecode:
          value: 7
          size: 3
        argument:
          size: 8
          byte_align: true
  8_bit_destination:
    operand_values:
      a_register:
        type: register
        register: a
        bytecode:
          value: 0
          size: 3
      i_register:
        type: register
        register: i
        bytecode:
          value: 2
          size: 3
      j_register:
        type: register
        register: j
        bytecode:
          value: 3
          size: 3
      indirect_addr:
        type: indirect_numeric
        bytecode:
          value: 6
          size: 3
        argument:
          size: 16
          byte_align: true
  16_bit_source:
    operand_values:
      mar_register:
        type: register
        register: mar
        bytecode:
          value: 2
          size: 3
      indirect_mar_register:
        type: indirect_register
        register: mar
        bytecode:
          value: 3
          size: 3
      indirect_addr:
        type: indirect_numeric
        bytecode:
          value: 6
          size: 3
        argument:
          size: 16
          byte_align: true
      immediate_value:
        type: numeric
        bytecode:
          value: 7
          size: 3
        argument:
          size: 16
          byte_align: true
  16_bit_destination:
    operand_values:
      mar_register:
        type: register
        register: mar
        bytecode:
          value: 2
          size: 3
      indirect_mar_register:
        type: indirect_register
        register: mar
        bytecode:
          value: 3
          size: 3
      indirect_addr:
        type: indirect_numeric
        bytecode:
          value: 6
          size: 3
        argument:
          size: 16
          byte_align: true
  address_source:
    operand_values:
      indirect_addr:
        type: indirect_numeric
        bytecode:
          value: 2
          size: 2
        argument:
          size: 16
          byte_align: true
      immediate_value:
        type: numeric
        bytecode:
          value: 3
          size: 2
        argument:
          size: 16
          byte_align: true
  incrementable_destination:
    operand_values:
      i_register:
        type: register
        register: i
        bytecode:
          value: 0
          size: 2
      j_register:
        type: register
        register: j
        bytecode:
          value: 1
          size: 2
      mar_register:
        type: register
        register: mar
        bytecode:
          value: 3
          size: 2
instructions:
  nop:
    bytecode:
      value: 0
      size: 8
  hlt:
    bytecode:
      value: 1
      size: 8
  jmp:
    bytecode:
      value: 11
      size: 6
    operands:
      count: 1
      operand_sets:
        list:
          - address_source
  jc:
    bytecode:
      value: 12
      size: 6
    operands:
      count: 1
      operand_sets:
        list:
          - address_source
  jz:
    bytecode:
      value: 13
      size: 6
    operands:
      count: 1
      operand_sets:
        list:
          - address_source
  jeq:
    bytecode:
      value: 2
      size: 3
    operands:
      count: 2
      operand_sets:
        reverse_argument_order: true
        list:
          - address_source
          - 8_bit_source
        disallowed_pairs:
          - [indirect_addr, a_register]
          - [immediate_value, a_register]
          - [indirect_addr, indirect_addr]
  mov:
    bytecode:
      value: 2
      size: 2
    operands:
      count: 2
      operand_sets:
        list:
          - 8_bit_destination
          - 8_bit_source
        disallowed_pairs:
          - [a_register, a_register]
          - [i_register, i_register]
          - [j_register, j_register]
      specific_operands:
        a_mar:
          list:
            a:
              type: register
              register: a
              bytecode:
                value: 0
                size: 3
            mar:
              type: indirect_register
              register: mar
              bytecode:
                value: 0
                size: 3
        i_mar:
          list:
            a:
              type: register
              register: i
              bytecode:
                value: 0b010
                size: 3
            mar:
              type: indirect_register
              register: mar
              bytecode:
                value: 0b010
                size: 3
        j_mar:
          list:
            a:
              type: register
              register: j
              bytecode:
                value: 0b011
                size: 3
            mar:
              type: indirect_register
              register: mar
              bytecode:
                value: 0b011
                size: 3
  add:
    bytecode:
      value: 23
      size: 5
    operands:
      count: 1
      operand_sets:
        list:
          - 8_bit_source
  sub:
    bytecode:
      value: 25
      size: 5
    operands:
      count: 1
      operand_sets:
        list:
          - 8_bit_source
  inc:
    bytecode:
      value: 54
      size: 6
    operands:
      count: 1
      operand_sets:
        list:
          - incrementable_destination
  dec:
    bytecode:
      value: 55
      size: 6
    operands:
      count: 1
      operand_sets:
        list:
          - incrementable_destination
  swap:
    bytecode:
      value: 1020
      size: 10
      endian: big
    operands:
      count: 2
      operand_sets:
        list:
          - 8_bit_destination
          - 8_bit_destination
        disallowed_pairs:
          - [a_register, a_register]
          - [i_register, i_register]
          - [j_register, j_register]
          - [indirect_addr, indirect_addr]
  mov2:
    bytecode:
      value: 1021
      size: 10
      endian: big
    operands:
      count: 2
      operand_sets:
        list:
          - 16_bit_destination
          - 16_bit_source
        disallowed_pairs:
          - [mar_register, mar_register]
          - [indirect_mar_register, mar_register]
          - [indirect_mar_register, indirect_mar_register]
          - [indirect_mar_register, indirect_addr]
          - [indirect_addr, mar]
          - [indirect_addr, indirect_mar_register]
          - [indirect_addr, indirect_addr]